### ISSUE TITLE
Add a video

### ISSUE THREAD

**Issue by germanattanasio** [ssudheen/Watson-Rover#1]
We need to include a video to describe the project and how it works

**Comment by germanattanasio** [comment]
The video is: https://vimeo.com/ibmwatson/review/130135196/ededb6b90f

**Comment by ssudheen** [comment]
Thanks !!

Been bit busy and missed your mail. This comes to my gmail. Will buzz you
in evening. Need some small help.

Regards
Sudhee

On Fri, Jul 3, 2015 at 4:34 AM, German Attanasio Ruiz <
notifications@github.com> wrote:

> Closed #1 https://github.com/ssudheen/Watson-Rover/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ssudheen/Watson-Rover/issues/1#event-346849108.

## 

Cheers
Sudhee

http://www.linkedin.com/in/sudhee

**Comment by germanattanasio** [comment]
YOu can add your picture, name and ibm email address to your github account so that it get linked to your github account
